name: Add High Priority Milestone

on:
  issues:
    types: [labeled]

jobs:
  add-milestone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run script to add milestone
      run: node .github/scripts/add-milestone.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
